services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: supply_chain
      POSTGRES_USER: sc_user
      POSTGRES_PASSWORD: sc_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./warehouse/schema/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redpanda:
    image: redpandadata/redpanda:v24.2.7
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 512M
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
    ports:
      - "9092:9092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

volumes:
  postgres_data:
  redpanda_data:
